name: GameOceanCore
version: '${project.version}'
main: net.gameocean.core.GameOceanCore
api-version: '1.21'
description: Le Core central du réseau GameOcean
author: GameOcean
depend: [Vault]
softdepend: [GameOceanRank, floodgate, Geyser-Spigot]

commands:
  build:
    description: Active/désactive le mode construction dans le lobby
    usage: /build
    permission: gameocean.build.admin
    permission-message: §cVous n'avez pas la permission d'utiliser cette commande.
  setspawn:
    description: Définit le point de spawn du lobby (OP uniquement)
    usage: /setspawn
    permission-message: Seuls les opérateurs peuvent utiliser cette commande.
  accept:
    description: Accepte les conditions d'utilisation ou une invitation d'appartement
    usage: /accept [joueur]
  decline:
    description: Refuse les conditions d'utilisation
    usage: /decline
  invite:
    description: Invite un joueur dans son appartement
    usage: /invite <joueur>
  bw:
    description: Commandes d'administration Bedwars
    usage: /bw <build|create|setwaiting|setbounds|team|setspawn|setbed|addnpc|addgen|save|info|list|join|leave|start|stop>
    permission: gameocean.bedwars.admin
    permission-message: §cVous n'avez pas la permission d'utiliser cette commande.
  world:
    description: Gestion des mondes
    usage: /world <list|load|unload|create|delete|tp|info|autoload>
    permission: gameocean.world.admin
    permission-message: §cVous n'avez pas la permission d'utiliser cette commande.
  app:
    description: Gestion du mode APARTMENT
    usage: /app admin <setdefault|tp|createtemplate> [nom]
  friend:
    description: Gestion des amis
    usage: /friend <add|accept|deny|remove|list> [joueur]
    aliases: [f, amis]
